// Generated by CoffeeScript 1.3.3
(function() {
  var resourceful;

  resourceful = require('resourceful');

  exports.Task = resourceful.define('task', function() {
    this.use('memory');
    this.string('name');
    return this.bool('completed');
  });

}).call(this);
