// Generated by CoffeeScript 1.3.3
(function() {
  var assert, request, suite, vows;

  vows = require('vows');

  assert = require('assert');

  request = require('request');

  suite = vows.describe('Blegh');

  suite.addBatch({
    'The Blegh': {
      'when running': {
        topic: function() {
          request({
            uri: 'http://localhost:3010/'
          }, this.callback);
        },
        "should respond with status of 200": function(e, res, body) {
          return assert.equal(res.statusCode, 200);
        }
      }
    }
  });

  suite.run();

}).call(this);
