// Generated by CoffeeScript 1.3.3
(function() {
  var assert, data, request, suite, vows;

  vows = require('vows');

  assert = require('assert');

  request = require('request');

  data = require('../data.js');

  suite = vows.describe('Todos');

  suite.addBatch({
    'Todos': {
      'http server': {
        topic: function() {
          request({
            uri: 'http://localhost:3010/'
          }, this.callback);
        },
        "should respond with status of 200": function(e, res, body) {
          return assert.equal(res.statusCode, 200);
        }
      },
      'data model': {
        'tasks': {
          topic: function() {
            return data.Task.create({
              'name': 'Foo',
              'completed': false
            }, this.callback);
          },
          "should be a Task": function(topic) {
            return assert.ok(topic instanceof data.Task);
          },
          "should be named Foo": function(topic) {
            return assert.equal(topic.name, 'Foo');
          },
          "should be possible to set completed": function(topic) {
            assert.doesNotThrow(function() {
              return topic.completed = true;
            });
            return assert.ok(topic.completed);
          }
        }
      }
    }
  });

  suite.run();

}).call(this);
